concurrency: 64
per_domain_rate_limit: 2        
timeout_secs: 15
retries: 2
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
scan_interval_hours: 6
rescan_unchanged_secret_check: false   